export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_LOADING = "SET_LOADING";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_TYPE = "GET_TYPE";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const GET_PAGE_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_BY_TYPE = "GET_PRODUCT_BY_TYPE";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CHANGE_QUANTITY_ITEM = "CHANGE_QUANTITY_ITEM";
export const INCREASE_QUANTITY_ITEM = "INCREASE_QUANTITY_ITEM";
export const REDUCTION_QUANTITY_ITEM = "REDUCTION_QUANTITY_ITEM";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";

export const CHECKOUT = "CHECKOUT";
export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";

export const SET_USER = "SET_USER";
export const UPDATE_USER = "UPDATE_USER";
